


% LAGG TILL SOKVAG OCH FLYTTA FUNKTION TILL 2MOD
serier = {'C:\Documents and Settings\Fredrik Edin\Mina dokument\Neuron\STANDARDFILER\MYSIMS\DTF\SIM_SERIER\DTF_delay\SERIES-delay-as-50NMDA30del15msG.txt', ...
    'C:\Documents and Settings\Fredrik Edin\Mina dokument\Neuron\STANDARDFILER\MYSIMS\DTF\SIM_SERIER\DTF_delay\SERIES-delay-as-25NMDA30del15msG.txt', ...
    'C:\Documents and Settings\Fredrik Edin\Mina dokument\Neuron\STANDARDFILER\MYSIMS\DTF\SIM_SERIER\DTF_delay\SERIES-delay-as0NMDA30del15msG.txt', ...
    'C:\Documents and Settings\Fredrik Edin\Mina dokument\Neuron\STANDARDFILER\MYSIMS\DTF\SIM_SERIER\DTF_delay\SERIES-delay-as25NMDA30del15msG.txt', ...
    'C:\Documents and Settings\Fredrik Edin\Mina dokument\Neuron\STANDARDFILER\MYSIMS\DTF\SIM_SERIER\DTF_delay\SERIES-delay-as50NMDA30del15msG.txt', ...
    'C:\Documents and Settings\Fredrik Edin\Mina dokument\Neuron\STANDARDFILER\MYSIMS\DTF\SIM_SERIER\DTF_delay\SERIES-delay-as75NMDA30del15msG.txt', ...
    'C:\Documents and Settings\Fredrik Edin\Mina dokument\Neuron\STANDARDFILER\MYSIMS\DTF\SIM_SERIER\DTF_delay\SERIES-delay-as-75NMDA70del15msG.txt', ...
    'C:\Documents and Settings\Fredrik Edin\Mina dokument\Neuron\STANDARDFILER\MYSIMS\DTF\SIM_SERIER\DTF_delay\SERIES-delay-as-50NMDA70del15msG.txt', ...
    'C:\Documents and Settings\Fredrik Edin\Mina dokument\Neuron\STANDARDFILER\MYSIMS\DTF\SIM_SERIER\DTF_delay\SERIES-delay-as-25NMDA70del15msG.txt', ...
    'C:\Documents and Settings\Fredrik Edin\Mina dokument\Neuron\STANDARDFILER\MYSIMS\DTF\SIM_SERIER\DTF_delay\SERIES-delay-as0NMDA70del15msG.txt', ...
    'C:\Documents and Settings\Fredrik Edin\Mina dokument\Neuron\STANDARDFILER\MYSIMS\DTF\SIM_SERIER\DTF_delay\SERIES-delay-as25NMDA70del15msG.txt', ...
    'C:\Documents and Settings\Fredrik Edin\Mina dokument\Neuron\STANDARDFILER\MYSIMS\DTF\SIM_SERIER\DTF_delay\SERIES-delay-as50NMDA70del15msG.txt', ...
    'C:\Documents and Settings\Fredrik Edin\Mina dokument\Neuron\STANDARDFILER\MYSIMS\DTF\SIM_SERIER\DTF_delay\SERIES-delay-as75NMDA70del15msG.txt', ...
    'C:\Documents and Settings\Fredrik Edin\Mina dokument\Neuron\STANDARDFILER\MYSIMS\DTF\SIM_SERIER\DTF_delay\SERIES-delay-as-75NMDA100del15msG.txt', ...
    'C:\Documents and Settings\Fredrik Edin\Mina dokument\Neuron\STANDARDFILER\MYSIMS\DTF\SIM_SERIER\DTF_delay\SERIES-delay-as-50NMDA100del15msG.txt', ...
    'C:\Documents and Settings\Fredrik Edin\Mina dokument\Neuron\STANDARDFILER\MYSIMS\DTF\SIM_SERIER\DTF_delay\SERIES-delay-as-25NMDA100del15msG.txt', ...
    'C:\Documents and Settings\Fredrik Edin\Mina dokument\Neuron\STANDARDFILER\MYSIMS\DTF\SIM_SERIER\DTF_delay\SERIES-delay-as0NMDA100del15msG.txt', ...
    'C:\Documents and Settings\Fredrik Edin\Mina dokument\Neuron\STANDARDFILER\MYSIMS\DTF\SIM_SERIER\DTF_delay\SERIES-delay-as25NMDA100del15msG.txt', ...
    'C:\Documents and Settings\Fredrik Edin\Mina dokument\Neuron\STANDARDFILER\MYSIMS\DTF\SIM_SERIER\DTF_delay\SERIES-delay-as50NMDA100del15msG.txt', ...
    'C:\Documents and Settings\Fredrik Edin\Mina dokument\Neuron\STANDARDFILER\MYSIMS\DTF\SIM_SERIER\DTF_delay\SERIES-delay-as75NMDA100del15msG.txt', ...
    'C:\Documents and Settings\Fredrik Edin\Mina dokument\Neuron\STANDARDFILER\MYSIMS\DTF\SIM_SERIER\DTF_cue_bada\SERIES-cue_bada-as-75NMDA30del15msG.txt', ...
    'C:\Documents and Settings\Fredrik Edin\Mina dokument\Neuron\STANDARDFILER\MYSIMS\DTF\SIM_SERIER\DTF_cue_bada\SERIES-cue_bada-as-50NMDA30del15msG.txt', ...
    'C:\Documents and Settings\Fredrik Edin\Mina dokument\Neuron\STANDARDFILER\MYSIMS\DTF\SIM_SERIER\DTF_cue_bada\SERIES-cue_bada-as-25NMDA30del15msG.txt', ...
    'C:\Documents and Settings\Fredrik Edin\Mina dokument\Neuron\STANDARDFILER\MYSIMS\DTF\SIM_SERIER\DTF_cue_bada\SERIES-cue_bada-as0NMDA30del15msG.txt', ...
    'C:\Documents and Settings\Fredrik Edin\Mina dokument\Neuron\STANDARDFILER\MYSIMS\DTF\SIM_SERIER\DTF_cue_bada\SERIES-cue_bada-as25NMDA30del15msG.txt', ...
    'C:\Documents and Settings\Fredrik Edin\Mina dokument\Neuron\STANDARDFILER\MYSIMS\DTF\SIM_SERIER\DTF_cue_bada\SERIES-cue_bada-as50NMDA30del15msG.txt', ...
    'C:\Documents and Settings\Fredrik Edin\Mina dokument\Neuron\STANDARDFILER\MYSIMS\DTF\SIM_SERIER\DTF_cue_bada\SERIES-cue_bada-as75NMDA30del15msG.txt', ...
    'C:\Documents and Settings\Fredrik Edin\Mina dokument\Neuron\STANDARDFILER\MYSIMS\DTF\SIM_SERIER\DTF_cue_bada\SERIES-cue_bada-as-75NMDA70del15msG.txt', ...
    'C:\Documents and Settings\Fredrik Edin\Mina dokument\Neuron\STANDARDFILER\MYSIMS\DTF\SIM_SERIER\DTF_cue_bada\SERIES-cue_bada-as-50NMDA70del15msG.txt', ...
    'C:\Documents and Settings\Fredrik Edin\Mina dokument\Neuron\STANDARDFILER\MYSIMS\DTF\SIM_SERIER\DTF_cue_bada\SERIES-cue_bada-as-25NMDA70del15msG.txt', ...
    'C:\Documents and Settings\Fredrik Edin\Mina dokument\Neuron\STANDARDFILER\MYSIMS\DTF\SIM_SERIER\DTF_cue_bada\SERIES-cue_bada-as0NMDA70del15msG.txt', ...
    'C:\Documents and Settings\Fredrik Edin\Mina dokument\Neuron\STANDARDFILER\MYSIMS\DTF\SIM_SERIER\DTF_cue_bada\SERIES-cue_bada-as25NMDA70del15msG.txt', ...
    'C:\Documents and Settings\Fredrik Edin\Mina dokument\Neuron\STANDARDFILER\MYSIMS\DTF\SIM_SERIER\DTF_cue_bada\SERIES-cue_bada-as50NMDA70del15msG.txt', ...
    'C:\Documents and Settings\Fredrik Edin\Mina dokument\Neuron\STANDARDFILER\MYSIMS\DTF\SIM_SERIER\DTF_cue_bada\SERIES-cue_bada-as75NMDA70del15msG.txt', ...
    'C:\Documents and Settings\Fredrik Edin\Mina dokument\Neuron\STANDARDFILER\MYSIMS\DTF\SIM_SERIER\DTF_cue_bada\SERIES-cue_bada-as-75NMDA100del15msG.txt', ...
    'C:\Documents and Settings\Fredrik Edin\Mina dokument\Neuron\STANDARDFILER\MYSIMS\DTF\SIM_SERIER\DTF_cue_bada\SERIES-cue_bada-as-50NMDA100del15msG.txt', ...
    'C:\Documents and Settings\Fredrik Edin\Mina dokument\Neuron\STANDARDFILER\MYSIMS\DTF\SIM_SERIER\DTF_cue_bada\SERIES-cue_bada-as-25NMDA100del15msG.txt', ...
    'C:\Documents and Settings\Fredrik Edin\Mina dokument\Neuron\STANDARDFILER\MYSIMS\DTF\SIM_SERIER\DTF_cue_bada\SERIES-cue_bada-as0NMDA100del15msG.txt', ...
    'C:\Documents and Settings\Fredrik Edin\Mina dokument\Neuron\STANDARDFILER\MYSIMS\DTF\SIM_SERIER\DTF_cue_bada\SERIES-cue_bada-as50NMDA100del15msG.txt', ...
    'C:\Documents and Settings\Fredrik Edin\Mina dokument\Neuron\STANDARDFILER\MYSIMS\DTF\SIM_SERIER\DTF_cue_bada\SERIES-cue_bada-as75NMDA100del15msG.txt', ...
    'C:\Documents and Settings\Fredrik Edin\Mina dokument\Neuron\STANDARDFILER\MYSIMS\DTF\SIM_SERIER\DTF_cue_PPC\SERIES-cue_PPC-as-75NMDA30del15msG.txt', ... % Cue till PPC
    'C:\Documents and Settings\Fredrik Edin\Mina dokument\Neuron\STANDARDFILER\MYSIMS\DTF\SIM_SERIER\DTF_cue_PPC\SERIES-cue_PPC-as-50NMDA30del15msG.txt', ...
    'C:\Documents and Settings\Fredrik Edin\Mina dokument\Neuron\STANDARDFILER\MYSIMS\DTF\SIM_SERIER\DTF_cue_PPC\SERIES-cue_PPC-as-25NMDA30del15msG.txt', ...
    'C:\Documents and Settings\Fredrik Edin\Mina dokument\Neuron\STANDARDFILER\MYSIMS\DTF\SIM_SERIER\DTF_cue_PPC\SERIES-cue_PPC-as0NMDA30del15msG.txt', ...
    'C:\Documents and Settings\Fredrik Edin\Mina dokument\Neuron\STANDARDFILER\MYSIMS\DTF\SIM_SERIER\DTF_cue_PPC\SERIES-cue_PPC-as25NMDA30del15msG.txt', ...
    'C:\Documents and Settings\Fredrik Edin\Mina dokument\Neuron\STANDARDFILER\MYSIMS\DTF\SIM_SERIER\DTF_cue_PPC\SERIES-cue_PPC-as50NMDA30del15msG.txt', ...
    'C:\Documents and Settings\Fredrik Edin\Mina dokument\Neuron\STANDARDFILER\MYSIMS\DTF\SIM_SERIER\DTF_cue_PPC\SERIES-cue_PPC-as75NMDA30del15msG.txt', ...
    'C:\Documents and Settings\Fredrik Edin\Mina dokument\Neuron\STANDARDFILER\MYSIMS\DTF\SIM_SERIER\DTF_cue_PPC\SERIES-cue_PPC-as-75NMDA70del15msG.txt', ...
    'C:\Documents and Settings\Fredrik Edin\Mina dokument\Neuron\STANDARDFILER\MYSIMS\DTF\SIM_SERIER\DTF_cue_PPC\SERIES-cue_PPC-as-50NMDA70del15msG.txt', ...
    'C:\Documents and Settings\Fredrik Edin\Mina dokument\Neuron\STANDARDFILER\MYSIMS\DTF\SIM_SERIER\DTF_cue_PPC\SERIES-cue_PPC-as-25NMDA70del15msG.txt', ...
    'C:\Documents and Settings\Fredrik Edin\Mina dokument\Neuron\STANDARDFILER\MYSIMS\DTF\SIM_SERIER\DTF_cue_PPC\SERIES-cue_PPC-as0NMDA70del15msG.txt', ...
    'C:\Documents and Settings\Fredrik Edin\Mina dokument\Neuron\STANDARDFILER\MYSIMS\DTF\SIM_SERIER\DTF_cue_PPC\SERIES-cue_PPC-as25NMDA70del15msG.txt', ...
    'C:\Documents and Settings\Fredrik Edin\Mina dokument\Neuron\STANDARDFILER\MYSIMS\DTF\SIM_SERIER\DTF_cue_PPC\SERIES-cue_PPC-as50NMDA70del15msG.txt', ...
    'C:\Documents and Settings\Fredrik Edin\Mina dokument\Neuron\STANDARDFILER\MYSIMS\DTF\SIM_SERIER\DTF_cue_PPC\SERIES-cue_PPC-as75NMDA70del15msG.txt', ...
    'C:\Documents and Settings\Fredrik Edin\Mina dokument\Neuron\STANDARDFILER\MYSIMS\DTF\SIM_SERIER\DTF_cue_PPC\SERIES-cue_PPC-as-50NMDA100del15msG.txt', ...
    'C:\Documents and Settings\Fredrik Edin\Mina dokument\Neuron\STANDARDFILER\MYSIMS\DTF\SIM_SERIER\DTF_cue_PPC\SERIES-cue_PPC-as-25NMDA100del15msG.txt', ...
    'C:\Documents and Settings\Fredrik Edin\Mina dokument\Neuron\STANDARDFILER\MYSIMS\DTF\SIM_SERIER\DTF_cue_PPC\SERIES-cue_PPC-as0NMDA100del15msG.txt', ...
    'C:\Documents and Settings\Fredrik Edin\Mina dokument\Neuron\STANDARDFILER\MYSIMS\DTF\SIM_SERIER\DTF_cue_PPC\SERIES-cue_PPC-as25NMDA100del15msG.txt', ...
    'C:\Documents and Settings\Fredrik Edin\Mina dokument\Neuron\STANDARDFILER\MYSIMS\DTF\SIM_SERIER\DTF_cue_PPC\SERIES-cue_PPC-as50NMDA100del15msG.txt', ...
    'C:\Documents and Settings\Fredrik Edin\Mina dokument\Neuron\STANDARDFILER\MYSIMS\DTF\SIM_SERIER\DTF_cue_PPC\SERIES-cue_PPC-as75NMDA100del15msG.txt',...
    'C:\Documents and Settings\Fredrik Edin\Mina dokument\Neuron\STANDARDFILER\MYSIMS\DTF\SIM_SERIER\DTF_vila\SERIES-vila-as-75NMDA30del15msG.txt', ... % vila
    'C:\Documents and Settings\Fredrik Edin\Mina dokument\Neuron\STANDARDFILER\MYSIMS\DTF\SIM_SERIER\DTF_vila\SERIES-vila-as-50NMDA30del15msG.txt', ...
    'C:\Documents and Settings\Fredrik Edin\Mina dokument\Neuron\STANDARDFILER\MYSIMS\DTF\SIM_SERIER\DTF_vila\SERIES-vila-as-25NMDA30del15msG.txt', ...
    'C:\Documents and Settings\Fredrik Edin\Mina dokument\Neuron\STANDARDFILER\MYSIMS\DTF\SIM_SERIER\DTF_vila\SERIES-vila-as0NMDA30del15msG.txt', ...
    'C:\Documents and Settings\Fredrik Edin\Mina dokument\Neuron\STANDARDFILER\MYSIMS\DTF\SIM_SERIER\DTF_vila\SERIES-vila-as25NMDA30del15msG.txt', ...
    'C:\Documents and Settings\Fredrik Edin\Mina dokument\Neuron\STANDARDFILER\MYSIMS\DTF\SIM_SERIER\DTF_vila\SERIES-vila-as50NMDA30del15msG.txt', ...
    'C:\Documents and Settings\Fredrik Edin\Mina dokument\Neuron\STANDARDFILER\MYSIMS\DTF\SIM_SERIER\DTF_vila\SERIES-vila-as75NMDA30del15msG.txt', ...
    'C:\Documents and Settings\Fredrik Edin\Mina dokument\Neuron\STANDARDFILER\MYSIMS\DTF\SIM_SERIER\DTF_vila\SERIES-vila-as-75NMDA70del15msG.txt', ...
    'C:\Documents and Settings\Fredrik Edin\Mina dokument\Neuron\STANDARDFILER\MYSIMS\DTF\SIM_SERIER\DTF_vila\SERIES-vila-as-50NMDA70del15msG.txt', ...
    'C:\Documents and Settings\Fredrik Edin\Mina dokument\Neuron\STANDARDFILER\MYSIMS\DTF\SIM_SERIER\DTF_vila\SERIES-vila-as-25NMDA70del15msG.txt', ...
    'C:\Documents and Settings\Fredrik Edin\Mina dokument\Neuron\STANDARDFILER\MYSIMS\DTF\SIM_SERIER\DTF_vila\SERIES-vila-as0NMDA70del15msG.txt', ...
    'C:\Documents and Settings\Fredrik Edin\Mina dokument\Neuron\STANDARDFILER\MYSIMS\DTF\SIM_SERIER\DTF_vila\SERIES-vila-as25NMDA70del15msG.txt', ...
    'C:\Documents and Settings\Fredrik Edin\Mina dokument\Neuron\STANDARDFILER\MYSIMS\DTF\SIM_SERIER\DTF_vila\SERIES-vila-as50NMDA70del15msG.txt', ...
    'C:\Documents and Settings\Fredrik Edin\Mina dokument\Neuron\STANDARDFILER\MYSIMS\DTF\SIM_SERIER\DTF_vila\SERIES-vila-as75NMDA70del15msG.txt', ...
    'C:\Documents and Settings\Fredrik Edin\Mina dokument\Neuron\STANDARDFILER\MYSIMS\DTF\SIM_SERIER\DTF_vila\SERIES-vila-as-75NMDA100del15msG.txt', ...
    'C:\Documents and Settings\Fredrik Edin\Mina dokument\Neuron\STANDARDFILER\MYSIMS\DTF\SIM_SERIER\DTF_vila\SERIES-vila-as-50NMDA100del15msG.txt', ...
    'C:\Documents and Settings\Fredrik Edin\Mina dokument\Neuron\STANDARDFILER\MYSIMS\DTF\SIM_SERIER\DTF_vila\SERIES-vila-as-25NMDA100del15msG.txt', ...
    'C:\Documents and Settings\Fredrik Edin\Mina dokument\Neuron\STANDARDFILER\MYSIMS\DTF\SIM_SERIER\DTF_vila\SERIES-vila-as0NMDA100del15msG.txt', ...
    'C:\Documents and Settings\Fredrik Edin\Mina dokument\Neuron\STANDARDFILER\MYSIMS\DTF\SIM_SERIER\DTF_vila\SERIES-vila-as25NMDA100del15msG.txt', ...
    'C:\Documents and Settings\Fredrik Edin\Mina dokument\Neuron\STANDARDFILER\MYSIMS\DTF\SIM_SERIER\DTF_vila\SERIES-vila-as50NMDA100del15msG.txt', ...
    'C:\Documents and Settings\Fredrik Edin\Mina dokument\Neuron\STANDARDFILER\MYSIMS\DTF\SIM_SERIER\DTF_vila\SERIES-vila-as75NMDA100del15msG.txt', ...
    'C:\Documents and Settings\Fredrik Edin\Mina dokument\Neuron\STANDARDFILER\MYSIMS\DTF\SIM_SERIER\koherens\SERIES-delay-koh0NMDA30del15ms.txt', ... % vila
    'C:\Documents and Settings\Fredrik Edin\Mina dokument\Neuron\STANDARDFILER\MYSIMS\DTF\SIM_SERIER\koherens\SERIES-delay-koh33NMDA30del15ms.txt', ...
    'C:\Documents and Settings\Fredrik Edin\Mina dokument\Neuron\STANDARDFILER\MYSIMS\DTF\SIM_SERIER\koherens\SERIES-delay-koh67NMDA30del15ms.txt', ...
    'C:\Documents and Settings\Fredrik Edin\Mina dokument\Neuron\STANDARDFILER\MYSIMS\DTF\SIM_SERIER\koherens\SERIES-delay-koh100NMDA30del15ms.txt', ...
    'C:\Documents and Settings\Fredrik Edin\Mina dokument\Neuron\STANDARDFILER\MYSIMS\DTF\SIM_SERIER\koherens\SERIES-delay-koh133NMDA30del15ms.txt', ...
    'C:\Documents and Settings\Fredrik Edin\Mina dokument\Neuron\STANDARDFILER\MYSIMS\DTF\SIM_SERIER\koherens\SERIES-delay-koh0NMDA70del15ms.txt', ...
    'C:\Documents and Settings\Fredrik Edin\Mina dokument\Neuron\STANDARDFILER\MYSIMS\DTF\SIM_SERIER\koherens\SERIES-delay-koh33NMDA70del15ms.txt', ...
    'C:\Documents and Settings\Fredrik Edin\Mina dokument\Neuron\STANDARDFILER\MYSIMS\DTF\SIM_SERIER\koherens\SERIES-delay-koh67NMDA70del15ms.txt', ...
    'C:\Documents and Settings\Fredrik Edin\Mina dokument\Neuron\STANDARDFILER\MYSIMS\DTF\SIM_SERIER\koherens\SERIES-delay-koh100NMDA70del15ms.txt', ...
    'C:\Documents and Settings\Fredrik Edin\Mina dokument\Neuron\STANDARDFILER\MYSIMS\DTF\SIM_SERIER\koherens\SERIES-delay-koh133NMDA70del15ms.txt', ...
    'C:\Documents and Settings\Fredrik Edin\Mina dokument\Neuron\STANDARDFILER\MYSIMS\DTF\SIM_SERIER\koherens\SERIES-delay-koh0NMDA100del15ms.txt', ...
    'C:\Documents and Settings\Fredrik Edin\Mina dokument\Neuron\STANDARDFILER\MYSIMS\DTF\SIM_SERIER\koherens\SERIES-delay-koh33NMDA100del15ms.txt', ...
    'C:\Documents and Settings\Fredrik Edin\Mina dokument\Neuron\STANDARDFILER\MYSIMS\DTF\SIM_SERIER\koherens\SERIES-delay-koh67NMDA100del15ms.txt', ...
    'C:\Documents and Settings\Fredrik Edin\Mina dokument\Neuron\STANDARDFILER\MYSIMS\DTF\SIM_SERIER\koherens\SERIES-delay-koh100NMDA100del15ms.txt', ...
    'C:\Documents and Settings\Fredrik Edin\Mina dokument\Neuron\STANDARDFILER\MYSIMS\DTF\SIM_SERIER\koherens\SERIES-delay-koh133NMDA100del15ms.txt'};
for i = 1:length(serier)
    showCatalog(serier{i})
    r = '';
    str = 'is file ok (y/n)?';
    while ~(strcmp(r,'y') | strcmp(r,'n'))
        r = input(str,'s');
        if strcmp(r,'y')
            res(i) = 1;
        elseif strcmp(r,'n')
            res(i) = 0;
        end
        str = 'again: (y/n)';
    end
end


for i = 1:length(serier)
    if ~res(i)
        ind = find(serier{i}=='\');
        disp(serier{i}(ind(end)+1:end))
    end
end
    